<?php
$title = 'ประวัติการเข้างาน - ระบบบริหารเงินเดือน';
require_once __DIR__ . '/../lib/db.php';
require_once __DIR__ . '/../lib/attendance.php';

if (!isset($_SESSION['username'])) {
    header('Location: /login');
    exit;
}

$settings = getAttendanceSettings($connection);
$now = attendanceNow($settings);
$months = attendanceMonthNames();
$selectedMonth = strtolower(trim((string) ($_GET['month'] ?? $now->format('F'))));
if (!isset($months[$selectedMonth])) $selectedMonth = strtolower($now->format('F'));
$selectedYear = filter_var($_GET['year'] ?? $now->format('Y'), FILTER_VALIDATE_INT) ?: (int) $now->format('Y');
if ($selectedYear < 2000 || $selectedYear > 2200) $selectedYear = (int) $now->format('Y');
$selectedId = trim((string) ($_GET['employee_id'] ?? $_GET['id'] ?? ''));
if ($selectedId !== '' && !ctype_digit($selectedId)) $selectedId = '';
$escape = static fn (mixed $value): string => htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8');
$jobLabels = ['executive'=>'เจ้าหน้าที่','manager'=>'ผู้จัดการ','director'=>'ผู้อำนวยการ','accountant'=>'นักบัญชี','chief'=>'หัวหน้าฝ่าย'];
$initials = static function (string $name): string { $parts=preg_split('/\s+/u',trim($name))?:[];return $parts?mb_substr($parts[0],0,1,'UTF-8').(count($parts)>1?mb_substr($parts[count($parts)-1],0,1,'UTF-8'):''):'พ'; };
$monthShort = [1=>'ม.ค.',2=>'ก.พ.',3=>'มี.ค.',4=>'เม.ย.',5=>'พ.ค.',6=>'มิ.ย.',7=>'ก.ค.',8=>'ส.ค.',9=>'ก.ย.',10=>'ต.ค.',11=>'พ.ย.',12=>'ธ.ค.'];

$employees = attendanceEmployeeList($connection, $now->format('Y-m-d'));
$departments = [];
$departmentResult = mysqli_query($connection, 'SELECT Depart_id, Depart_name FROM department ORDER BY Depart_name');
if ($departmentResult) while ($department=mysqli_fetch_assoc($departmentResult)) $departments[]=$department;
$selectedEmployee = null;
foreach ($employees as $employee) if ((string)$employee['Employee_id']===$selectedId) { $selectedEmployee=$employee; break; }

$metrics = $selectedEmployee ? attendancePeriodMetrics($connection, (int)$selectedEmployee['Employee_id'], $selectedYear, $selectedMonth) : null;
$historyRows = $metrics ? attendanceHistoryRows($metrics) : [];
$availableYears = [(int)$now->format('Y'),$selectedYear];
$yearResult = mysqli_query($connection, 'SELECT DISTINCT YEAR(attendance_date) AS attendance_year FROM attendance ORDER BY attendance_year DESC');
if ($yearResult) while ($yearRow=mysqli_fetch_assoc($yearResult)) $availableYears[]=(int)$yearRow['attendance_year'];
$availableYears=array_values(array_unique($availableYears));rsort($availableYears);
?>

<div class="w-full space-y-4" data-attendance-history-page>
    <header class="pb-3 border-b border-[#dedede]"><h1 class="text-lg font-semibold text-[#202223]">ประวัติการเข้างาน</h1><p class="mt-0.5 text-sm text-[#6d7175]">ตรวจสอบเวลาเข้า–ออก วันขาดงาน และสถิติการมาสายรายเดือน</p></header>

    <section aria-labelledby="historyAttendanceEmployeeTitle">
        <div class="mb-2 flex items-center justify-between"><h2 id="historyAttendanceEmployeeTitle" class="text-sm font-bold">พนักงาน</h2><span class="text-xs text-[#6d7175]">เลือกได้ครั้งละ 1 คน</span></div>
        <div class="rounded-lg border border-[#dedede] bg-white p-3 sm:p-4">
            <?php if (!$selectedEmployee): ?><div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div class="flex items-center gap-3"><span class="flex h-10 w-10 items-center justify-center rounded-full bg-[#f2f2f2] text-[#8a8580]"><i class="fa-solid fa-user-clock"></i></span><div><p class="text-sm font-bold">ยังไม่ได้เลือกพนักงาน</p><p class="text-xs text-[#6d7175]">ค้นหาด้วยชื่อ รหัส แผนก หรือตำแหน่ง</p></div></div><button type="button" data-open-employee-picker class="min-h-9 rounded-md bg-[#303030] px-3 text-sm font-medium text-white"><i class="fa-solid fa-users mr-2"></i>เลือกพนักงาน</button></div>
            <?php else: ?><div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div class="flex min-w-0 items-center gap-3"><span class="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-[#eef6fd] text-sm font-bold text-[#0075de]"><?= $escape($initials($selectedEmployee['Name'])) ?></span><div class="min-w-0"><p class="truncate text-sm font-bold"><?= $escape($selectedEmployee['Name']) ?></p><p class="text-xs text-[#6d7175]"><?= $escape($selectedEmployee['Employee_id']) ?> · <?= $escape($selectedEmployee['Depart_name'] ?: 'ไม่ระบุแผนก') ?> · <?= $escape($jobLabels[$selectedEmployee['jobtitle']] ?? $selectedEmployee['jobtitle']) ?></p></div></div><button type="button" data-open-employee-picker class="min-h-9 rounded-md border border-[#d5d3d0] bg-white px-3 text-sm font-medium hover:bg-[#f6f5f4]"><i class="fa-solid fa-repeat mr-2"></i>เปลี่ยนพนักงาน</button></div><?php endif; ?>
        </div>
    </section>

    <?php if (!$selectedEmployee): ?>
        <section class="flex min-h-[300px] flex-col items-center justify-center rounded-lg border border-dashed border-[#d5d3d0] bg-white px-5 py-10 text-center"><span class="flex h-12 w-12 items-center justify-center rounded-full bg-[#f2f2f2] text-[#8a8580]"><i class="fa-solid fa-calendar-check"></i></span><h2 class="mt-4 text-base font-bold">เลือกพนักงานเพื่อดูประวัติการเข้างาน</h2><p class="mt-1 text-sm text-[#6d7175]">ดูเวลาเข้า–ออก ชั่วโมงทำงาน วันขาด และนาทีที่มาสายในแต่ละงวด</p><button type="button" data-open-employee-picker class="mt-5 min-h-9 rounded-md bg-[#303030] px-3 text-sm font-medium text-white">เลือกพนักงาน</button></section>
    <?php else: ?>
        <section class="overflow-hidden rounded-lg border border-[#dedede] bg-white" aria-label="สรุปการเข้างาน"><div class="grid grid-cols-2 divide-x divide-y divide-[#e6e6e6] sm:grid-cols-5 sm:divide-y-0"><div class="p-3.5"><p class="text-xs text-[#6d7175]">วันทำงาน</p><p class="mt-1 text-lg font-bold"><?= (int)$metrics['expected_days'] ?> <span class="text-xs font-normal">วัน</span></p></div><div class="p-3.5"><p class="text-xs text-[#6d7175]">มาทำงาน</p><p class="mt-1 text-lg font-bold text-emerald-700"><?= (int)$metrics['attendance_days'] ?> <span class="text-xs font-normal">วัน</span></p></div><div class="p-3.5"><p class="text-xs text-[#6d7175]">ขาดงาน</p><p class="mt-1 text-lg font-bold text-red-700"><?= (int)$metrics['absence_days'] ?> <span class="text-xs font-normal">วัน</span></p></div><div class="p-3.5"><p class="text-xs text-[#6d7175]">มาสาย</p><p class="mt-1 text-lg font-bold text-amber-700"><?= (int)$metrics['late_count'] ?> <span class="text-xs font-normal">ครั้ง</span></p></div><div class="col-span-2 p-3.5 sm:col-span-1"><p class="text-xs text-[#6d7175]">มาสายรวม</p><p class="mt-1 text-lg font-bold"><?= (int)$metrics['late_minutes'] ?> <span class="text-xs font-normal">นาที</span></p></div></div><p class="border-t border-[#e6e6e6] px-3.5 py-2 text-xs text-[#6d7175]">คำนวณถึงวันที่ <?= $escape(date('d/m/Y',strtotime($metrics['completed_through']))) ?> โดยไม่รวมวันอนาคต วันหยุดประจำสัปดาห์ และวันหยุดที่ลงทะเบียนในระบบ</p></section>

        <section class="overflow-hidden rounded-lg border border-[#dedede] bg-white" aria-labelledby="attendanceHistoryListTitle">
            <header class="flex flex-col gap-3 border-b border-[#e6e6e6] p-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 id="attendanceHistoryListTitle" class="text-sm font-bold">รายการเข้างาน</h2><p class="mt-0.5 text-xs text-[#6d7175]"><?= $escape($months[$selectedMonth]) ?> พ.ศ. <?= $selectedYear+543 ?></p></div><form method="get" action="/attendance/history" class="grid grid-cols-2 gap-2"><input type="hidden" name="employee_id" value="<?= $escape($selectedEmployee['Employee_id']) ?>"><label class="sr-only" for="attendanceHistoryMonth">เดือน</label><select id="attendanceHistoryMonth" name="month" class="dashboard-period-select min-h-9 rounded-md border border-[#dedede] bg-white px-2 text-sm"><?php foreach($months as $value=>$label): ?><option value="<?= $escape($value) ?>" <?= $selectedMonth===$value?'selected':'' ?>><?= $escape($label) ?></option><?php endforeach; ?></select><label class="sr-only" for="attendanceHistoryYear">ปี</label><select id="attendanceHistoryYear" name="year" class="dashboard-period-select min-h-9 rounded-md border border-[#dedede] bg-white px-2 text-sm"><?php foreach($availableYears as $year): ?><option value="<?= $year ?>" <?= $selectedYear===$year?'selected':'' ?>>พ.ศ. <?= $year+543 ?></option><?php endforeach; ?></select></form></header>
            <?php if ($historyRows): ?>
                <section class="js-mobile-list-section md:hidden px-4"><div class="relative my-3"><i class="fa-solid fa-magnifying-glass absolute left-3 top-1/2 -translate-y-1/2 text-[#a39e98]"></i><input type="search" class="js-mobile-search min-h-10 w-full rounded-md border border-[#dedede] pl-10 pr-3 text-sm" placeholder="ค้นหาวันที่หรือสถานะ..."></div><div class="js-mobile-records divide-y divide-[#e6e6e6]"><?php foreach($historyRows as $index=>$row): ?><?php $meta=attendanceStatusMeta($row);$dateValue=new DateTimeImmutable($row['attendance_date']);$locationName=$row['check_in_geofence_name']??$row['check_out_geofence_name']??null;$locationLat=$row['check_in_latitude']??$row['check_out_latitude']??null;$locationLng=$row['check_in_longitude']??$row['check_out_longitude']??null;$locationAccuracy=$row['check_in_accuracy']??$row['check_out_accuracy']??null; ?><article class="js-mobile-record py-3" data-original="<?= $index ?>" data-search="<?= $escape(mb_strtolower($row['attendance_date'].' '.$meta['label'].' '.($locationName??''),'UTF-8')) ?>"><div class="flex items-center justify-between gap-3"><p class="text-sm font-bold"><?= $dateValue->format('j') ?> <?= $monthShort[(int)$dateValue->format('n')] ?> <?= (int)$dateValue->format('Y')+543 ?></p><span class="rounded-full px-2.5 py-1 text-xs font-semibold <?= $meta['class'] ?>"><?= $escape($meta['label']) ?></span></div><dl class="mt-3 grid grid-cols-[auto_1fr] gap-x-4 gap-y-1.5 text-xs"><dt class="text-[#6d7175]">เข้า</dt><dd class="text-right font-medium"><?= $row['check_in_at']?date('H:i',strtotime($row['check_in_at'])):'--' ?></dd><dt class="text-[#6d7175]">ออก</dt><dd class="text-right font-medium"><?= $row['check_out_at']?date('H:i',strtotime($row['check_out_at'])):'--' ?></dd><dt class="text-[#6d7175]">ทำงาน</dt><dd class="text-right font-medium"><?= $escape(attendanceFormatDuration($row['check_in_at'],$row['check_out_at'])) ?></dd><dt class="text-[#6d7175]">มาสาย</dt><dd class="text-right font-medium"><?= (int)$row['late_minutes']>0?(int)$row['late_minutes'].' นาที':'-' ?></dd><dt class="text-[#6d7175]">สถานที่</dt><dd class="text-right font-medium"><?= $escape($locationName ?: '-') ?><?php if($locationLat!==null&&$locationLng!==null): ?> <button type="button" data-location-view data-location-lat="<?= $escape($locationLat) ?>" data-location-lng="<?= $escape($locationLng) ?>" data-location-accuracy="<?= $escape($locationAccuracy) ?>" data-location-name="<?= $escape($locationName ?: 'ตำแหน่งเช็คชื่อ') ?>" class="ml-2 text-[#0075de]">ดูตำแหน่ง</button><?php endif; ?></dd></dl><?php if($row['check_in_at']&&!$row['check_out_at']): ?><p class="mt-2 text-xs text-amber-700"><i class="fa-solid fa-circle-exclamation mr-1"></i>ยังไม่มีเวลาออกงาน</p><?php endif; ?></article><?php endforeach; ?></div><div class="js-mobile-empty-filter hidden py-8 text-center text-sm text-[#6d7175]">ไม่พบรายการ</div></section>
                <div class="hidden md:block"><table class="js-data-table w-full text-left text-sm" data-export-name="ประวัติการเข้างาน <?= $escape($selectedEmployee['Name']) ?>"><thead class="border-b border-[#e6e6e6] bg-[#fafafa]"><tr><th class="px-4 py-3 text-xs font-semibold text-[#6d7175]">วันที่</th><th class="px-4 py-3 text-xs font-semibold text-[#6d7175]">เข้า</th><th class="px-4 py-3 text-xs font-semibold text-[#6d7175]">ออก</th><th class="px-4 py-3 text-xs font-semibold text-[#6d7175]">ชั่วโมงทำงาน</th><th class="px-4 py-3 text-xs font-semibold text-[#6d7175]">มาสาย</th><th class="px-4 py-3 text-xs font-semibold text-[#6d7175]">สถานที่</th><th class="px-4 py-3 text-xs font-semibold text-[#6d7175]">สถานะ</th></tr></thead><tbody class="divide-y divide-[#e6e6e6]"><?php foreach($historyRows as $row): ?><?php $meta=attendanceStatusMeta($row);$dateValue=new DateTimeImmutable($row['attendance_date']);$locationName=$row['check_in_geofence_name']??$row['check_out_geofence_name']??null;$locationLat=$row['check_in_latitude']??$row['check_out_latitude']??null;$locationLng=$row['check_in_longitude']??$row['check_out_longitude']??null;$locationAccuracy=$row['check_in_accuracy']??$row['check_out_accuracy']??null; ?><tr><td class="px-4 py-3 font-semibold"><?= $dateValue->format('j') ?> <?= $monthShort[(int)$dateValue->format('n')] ?> <?= (int)$dateValue->format('Y')+543 ?></td><td class="px-4 py-3"><?= $row['check_in_at']?date('H:i',strtotime($row['check_in_at'])):'--' ?></td><td class="px-4 py-3"><?= $row['check_out_at']?date('H:i',strtotime($row['check_out_at'])):'--' ?></td><td class="px-4 py-3"><?= $escape(attendanceFormatDuration($row['check_in_at'],$row['check_out_at'])) ?></td><td class="px-4 py-3"><?= (int)$row['late_minutes']>0?(int)$row['late_minutes'].' นาที':'-' ?></td><td class="px-4 py-3"><p class="font-medium"><?= $escape($locationName ?: '-') ?></p><?php if($locationLat!==null&&$locationLng!==null): ?><button type="button" data-location-view data-location-lat="<?= $escape($locationLat) ?>" data-location-lng="<?= $escape($locationLng) ?>" data-location-accuracy="<?= $escape($locationAccuracy) ?>" data-location-name="<?= $escape($locationName ?: 'ตำแหน่งเช็คชื่อ') ?>" class="mt-1 text-xs font-medium text-[#0075de]">ดูตำแหน่ง</button><?php endif; ?></td><td class="px-4 py-3"><span class="rounded-full px-2.5 py-1 text-xs font-semibold <?= $meta['class'] ?>"><?= $escape($meta['label']) ?></span><?php if($row['check_in_at']&&!$row['check_out_at']): ?><span class="ml-2 text-xs text-amber-700">ยังไม่ออกงาน</span><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div>
            <?php else: ?><div class="flex min-h-[240px] flex-col items-center justify-center px-5 py-10 text-center"><span class="flex h-11 w-11 items-center justify-center rounded-full bg-[#f2f2f2] text-[#8a8580]"><i class="fa-solid fa-calendar-xmark"></i></span><h3 class="mt-4 text-sm font-bold">ไม่มีรายการในงวดที่เลือก</h3><p class="mt-1 text-xs text-[#6d7175]">งวดนี้ยังไม่มีวันทำงานที่เสร็จสิ้นหรือรายการลงเวลา</p></div><?php endif; ?>
        </section>
    <?php endif; ?>

    <div id="attendanceLocationModal" class="fixed inset-0 z-[90] hidden items-center justify-center p-4" role="dialog" aria-modal="true" aria-labelledby="attendanceLocationTitle"><div class="absolute inset-0 bg-black/40" data-location-modal-close></div><div class="relative w-full max-w-lg overflow-hidden rounded-lg border border-[#dedede] bg-white shadow-2xl"><header class="flex items-start justify-between gap-3 border-b border-[#e6e6e6] p-4"><div><h2 id="attendanceLocationTitle" class="text-sm font-bold">ตำแหน่งเช็คชื่อ</h2><p data-location-modal-name class="mt-0.5 text-xs text-[#6d7175]"></p></div><button type="button" data-location-modal-close class="h-8 w-8 rounded-md hover:bg-[#f6f5f4]" aria-label="ปิด"><i class="fa-solid fa-xmark"></i></button></header><div id="attendanceLocationMap" class="h-[320px] w-full bg-[#ececec]"></div><p data-location-modal-accuracy class="border-t border-[#e6e6e6] px-4 py-3 text-xs text-[#6d7175]"></p></div></div>

    <?php $employeePickerEmployees=$employees;$employeePickerDepartments=$departments;$employeePickerSelectedId=$selectedEmployee?(string)$selectedEmployee['Employee_id']:'';$employeePickerJobLabels=$jobLabels;$employeePickerContext='attendance_history';$employeePickerExtraQuery='month='.rawurlencode($selectedMonth).'&year='.rawurlencode((string)$selectedYear);require __DIR__.'/components/employee_picker.php'; ?>
</div>
